### PR TITLE
TI-275 prune unnecessary gstreamer plugins

### PR DESCRIPTION
**Pull request by angelagit**

### CODE REVIEW

**Comment by dressupgeekout** [comment]
Oops, you've added the list of plugins twice, kinda.

Excerpt from `hula --host cosmos:cake`:

```
        "--disable-videoconvert",
        "--disable-videorate",
        "--disable-videoscale",
        "--disable-videotestsrc",
        "--disable-volume",
        "--enable-app",
        "alsa",
        "cdparanoia",
        "ivorbis",
        "libvisual",
        "ogg",
        "opus",
        "pango",
        "theora",
        "vorbis",
```

The call to `./configure` should only be using `*configure_flags` in this case

**Comment by dressupgeekout** [comment]
Once that gets fixed then this seems alright

```
configure: *** Plug-ins without external dependencies that will be built:
        app
configure: *** Plug-ins without external dependencies that will NOT be built:
        adder
        audioconvert
        audiorate
        audioresample
        audiotestsrc
        encoding
        gio
        playback
        subparse
        tcp
        typefind
        videoconvert
        videorate
        videoscale
        videotestsrc
        volume
configure: *** Plug-ins that have NOT been ported:
configure: *** Plug-ins with dependencies that will be built:
configure: *** Plug-ins with dependencies that will NOT be built:
         
        alsa
        cdparanoia
        ivorbisdec
        libvisual
        ogg
        opus
        pango
        theora
        vorbis
        ximagesink
        xvimagesink
```

**Comment by angelagit** [comment]
This is the code for the ./configure:
  cmd './configure', *(configure_flags += disabled_plugins += enabled_plugins)

Do you want to change this code, so "disabled_plugins" & "enabled_plugins" are not added to ./configure?
Also, I don't know how did you get:
        "--disable-videoconvert",
        "--disable-videorate",
        "--disable-videoscale",
        "--disable-videotestsrc",
        "--disable-volume",
        "--enable-app",

I don't see them in Hulafile from base (bw/develop branch)

**Comment by angelagit** [comment]
@dressupgeekout, can you try it again. I have updated the "configure_flags".

**Pull request merged**
